version: '3'

services:
  app:
    container_name: laravel-next-app
    build:
      context: .
      dockerfile: ./server/.docker/local/php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./server:/app
      - ./server/.docker/local/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql

  nginx:
    container_name: laravel-next-nginx
    build:
      context: .
      dockerfile: ./server/.docker/local/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./server/public:/app/public
      - ./server/.docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  mysql:
    container_name: laravel-next-mysql
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: laravel_next
      MYSQL_USER: laravel_next
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./server/.docker/local/mysql/data:/var/lib/mysql
      - ./server/.docker/local/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./server/.docker/local/mysql/logs:/var/log/mysql
      - ./server/.docker/local/mysql/mysql-docker-entrypoint.sql:/docker-entrypoint-initdb.d/mysql-docker-entrypoint.sql

  redis:
    container_name: laravel-next-redis
    image: redis:6.2-buster
    ports:
      - "6379:6379"

  queue:
    container_name: laravel-next-queue
    build:
      context: .
      dockerfile: ./server/.docker/local/php/Dockerfile
    working_dir: /app
    command: php artisan queue:work --tries=3
    volumes:
      - .:/app
      - ./server/.docker/local/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - app
      - nginx

  minio:
    container_name: laravel-next-minio
    image: minio/minio
    ports:
      - "9001:9001"
      - "9002:9002"
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9001 --console-address :9002"

  create-bucket:
    container_name: laravel-next-create-bucket
    image: minio/mc
    command: |
        /bin/sh -c
        until (mc config host add minio http://minio:9001 access_key secret_key) do echo 'wait until add host' && sleep 1; done;
        mc mb minio/public
        mc policy set public minio/public
        mc mb minio/private
        mc policy set private minio/private
    depends_on:
     - minio
